return {
	property = {
		{name = "スキン構成の保存 SaveSkinConfig", def = "OFF"},
		{name = "エラーメッセージ表示 DisplayErrorMessage", def = "ON"},
		{name = "画面解像度 Resolution", def = "FHD(1920x1080)"},
	},
	filepath = {
		{name = "設定ファイル Settings", def = "default1P.lua"},
		{name = "システムフォント Font", def = "mgenplus-1c-bold.ttf"},
		{name = "フレーム Frame", def = "default"},
		{name = "Frame2", def = "dpjam"},
		{name = "背景 Background", def = "default2.png"},
		{name = "汎用BGA/BGI NoBgaImage", def = "off.png"},
		{name = "鍵盤デザイン Device", def = "default"},
		{name = "グルーブゲージ GrooveGauge", def = "default"},
		{name = "スコアグラフ ScoreGraph", def = "off"},
		{name = "ソングプログレスバー SongProgress", def = "blue"},
		{name = "楽曲情報 SongInfo", def = "default"},
		{name = "BPM Bpm", def = "off"},
		{name = "スコア Score", def = "default"},
		{name = "スコアレート ScoreRate", def = "default"},
		{name = "MAXコンボ MaxCombo", def = "default"},
		{name = "自己ベストスコア差 DiffBestScore", def = "default"},
		{name = "ターゲットスコア差 DiffTargetScore", def = "default"},
		{name = "ランクペース RankPace", def = "off"},
		{name = "ジャッジカウント JudgeCount", def = "default"},
		{name = "タイムレフト TimeLeft", def = "default"},
		{name = "マスコット Mascot", def = "off.png"},
		{name = "動くマスコット MovingMascot", def = "off.png"},
		{name = "ぽみゅキャラ Pmchara", def = "off"},
		{name = "タイミングビジュアライザ TimingVisualizer", def = "off"},
		{name = "ヒットエラービジュアライザ HitErrorVisualizer", def = "off"},
		{name = "ジャッジグラフ JudgeGraph", def = "off"},
		{name = "BPMグラフ BpmGraph", def = "off"},
		{name = "レーン背景 LaneBackground", def = "default.png"},
		{name = "レーン Lane", def = "beat"},
		{name = "グロー Glow", def = "red"},
		{name = "判定ライン JudgeLine", def = "red"},
		{name = "ノーツ notes", def = "o2bar"},
		{name = "キービーム Keybeam", def = "off"},
		{name = "レーンカバー1P LaneCover1P", def = "default.png"},
		{name = "リフトカバー1P LiftCover1P", def = "default.png"},
		{name = "HIDDENカバー1P HiddenCover1P", def = "default.png"},
		{name = "フィニッシュカバー1P FinishCover1P", def = "default.png"},
		{name = "カバー数値 CoverDuration", def = "default"},
		{name = "ボム Bomb", def = "2"},
		{name = "判定文字 Judge", def = "11"},
		{name = "Combo", def = "1"},
		{name = "判定タイミング JudgeDetail", def = "default-fastslow"},
		{name = "ゴーストスコア GhostScore", def = "default-target"},
		{name = "ロード中演出 Loading", def = "default"},
		{name = "開始演出 Start", def = "default"},
		{name = "クリア演出 Clear", def = "off"},
		{name = "フルコンボ演出 FullCombo", def = "default"},
		{name = "閉店演出 Failed", def = "default"},
		{name = "終了演出 Close", def = "default"},
		{name = "拡張機能1 Extension1", def = "off"},
		{name = "拡張機能2 Extension2", def = "off"},
		{name = "拡張機能3 Extension3", def = "off"},
		{name = "拡張機能4 Extension4", def = "off"},
		{name = "拡張機能5 Extension5", def = "off"},
		{name = "拡張機能6 Extension6", def = "off"},
		{name = "拡張機能7 Extension7", def = "off"},
		{name = "拡張機能8 Extension8", def = "off"},
		{name = "拡張機能9 Extension9", def = "off"},
		{name = "拡張機能10 Extension10", def = "off"},
	},
	offset = {
	}
}